"""empty message

Revision ID: 06615a37b382
Revises: 
Create Date: 2021-05-08 17:07:26.110413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06615a37b382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight_goal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('curlsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rep', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('no_of_backbent', sa.Integer(), nullable=True),
    sa.Column('no_of_wristbent', sa.Integer(), nullable=True),
    sa.Column('no_of_elbowflare', sa.Integer(), nullable=True),
    sa.Column('no_of_shouldershrug', sa.Integer(), nullable=True),
    sa.Column('no_of_mistakes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('healthcondition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('illness', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ohpsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rep', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('no_of_bentknees', sa.Integer(), nullable=True),
    sa.Column('no_of_elbowposition', sa.Integer(), nullable=True),
    sa.Column('no_of_archedback', sa.Integer(), nullable=True),
    sa.Column('no_of_mistakes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planksession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rep', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('no_of_backbentupwards', sa.Integer(), nullable=True),
    sa.Column('no_of_stomachinwards', sa.Integer(), nullable=True),
    sa.Column('no_of_kneesbent', sa.Integer(), nullable=True),
    sa.Column('no_of_lookingstraight', sa.Integer(), nullable=True),
    sa.Column('no_of_loweringhips', sa.Integer(), nullable=True),
    sa.Column('no_of_archingback', sa.Integer(), nullable=True),
    sa.Column('no_of_mistakes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('squatsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('rep', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('no_of_kneesinward', sa.Integer(), nullable=True),
    sa.Column('no_of_toolow', sa.Integer(), nullable=True),
    sa.Column('no_of_bentforward', sa.Integer(), nullable=True),
    sa.Column('no_of_heelsraised', sa.Integer(), nullable=True),
    sa.Column('no_of_mistakes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squatsession')
    op.drop_table('planksession')
    op.drop_table('ohpsession')
    op.drop_table('healthcondition')
    op.drop_table('curlsession')
    op.drop_table('users')
    # ### end Alembic commands ###
