"""empty message

Revision ID: 203df3a58220
Revises: 9934465f9fee
Create Date: 2021-05-10 00:10:41.004866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '203df3a58220'
down_revision = '9934465f9fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MET',
    sa.Column('CODE', sa.Integer(), nullable=False),
    sa.Column('METS', sa.Float(), nullable=True),
    sa.Column('HEADING', sa.String(length=23), nullable=True),
    sa.Column('ACTIVITIES', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('CODE')
    )
    op.drop_table('MET_values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MET_values',
    sa.Column('CODE', sa.INTEGER(), server_default=sa.text('nextval(\'"MET_values_CODE_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('METS', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('HEADING', sa.VARCHAR(length=23), autoincrement=False, nullable=True),
    sa.Column('ACTIVITIES', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CODE', name='MET_values_pkey')
    )
    op.drop_table('MET')
    # ### end Alembic commands ###
