"""empty message

Revision ID: 602d9086abdd
Revises: 203df3a58220
Create Date: 2021-05-10 00:23:33.819536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '602d9086abdd'
down_revision = '203df3a58220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mettable',
    sa.Column('CODE', sa.Integer(), nullable=False),
    sa.Column('METS', sa.Float(), nullable=True),
    sa.Column('HEADING', sa.String(length=23), nullable=True),
    sa.Column('ACTIVITIES', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('CODE')
    )
    op.drop_table('MET')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MET',
    sa.Column('CODE', sa.INTEGER(), server_default=sa.text('nextval(\'"MET_CODE_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('METS', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('HEADING', sa.VARCHAR(length=23), autoincrement=False, nullable=True),
    sa.Column('ACTIVITIES', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CODE', name='MET_pkey')
    )
    op.drop_table('mettable')
    # ### end Alembic commands ###
