"""empty message

Revision ID: 9934465f9fee
Revises: 0c79e0c998a0
Create Date: 2021-05-09 23:36:27.622747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9934465f9fee'
down_revision = '0c79e0c998a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MET_values',
    sa.Column('CODE', sa.Integer(), nullable=False),
    sa.Column('METS', sa.Float(), nullable=True),
    sa.Column('HEADING', sa.String(length=23), nullable=True),
    sa.Column('ACTIVITIES', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('CODE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MET_values')
    # ### end Alembic commands ###
