"""empty message

Revision ID: 9957db20995a
Revises: 99a5a9ea38b5
Create Date: 2021-05-11 13:59:27.971244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9957db20995a'
down_revision = '99a5a9ea38b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mettable', sa.Column('activities', sa.String(length=255), nullable=True))
    op.add_column('mettable', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('mettable', sa.Column('heading', sa.String(length=23), nullable=True))
    op.add_column('mettable', sa.Column('met', sa.Float(), nullable=True))
    op.drop_column('mettable', 'METS')
    op.drop_column('mettable', 'HEADING')
    op.drop_column('mettable', 'ACTIVITIES')
    op.drop_column('mettable', 'CODE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mettable', sa.Column('CODE', sa.INTEGER(), server_default=sa.text('nextval(\'"mettable_CODE_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('mettable', sa.Column('ACTIVITIES', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mettable', sa.Column('HEADING', sa.VARCHAR(length=23), autoincrement=False, nullable=True))
    op.add_column('mettable', sa.Column('METS', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('mettable', 'met')
    op.drop_column('mettable', 'heading')
    op.drop_column('mettable', 'code')
    op.drop_column('mettable', 'activities')
    # ### end Alembic commands ###
