"""empty message

Revision ID: 99a5a9ea38b5
Revises: 602d9086abdd
Create Date: 2021-05-11 07:49:09.445384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a5a9ea38b5'
down_revision = '602d9086abdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curlsession', sa.Column('start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curlsession', 'start_time')
    # ### end Alembic commands ###
