"""empty message

Revision ID: c4730d14f909
Revises: 9957db20995a
Create Date: 2021-05-11 18:09:55.913184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4730d14f909'
down_revision = '9957db20995a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mets_table',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('met', sa.Float(), nullable=True),
    sa.Column('heading', sa.String(length=50), nullable=True),
    sa.Column('activities', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.add_column('mettable', sa.Column('ACTIVITIES', sa.String(length=255), nullable=True))
    op.add_column('mettable', sa.Column('CODE', sa.Integer(), nullable=False))
    op.add_column('mettable', sa.Column('HEADING', sa.String(length=23), nullable=True))
    op.add_column('mettable', sa.Column('METS', sa.Float(), nullable=True))
    op.drop_column('mettable', 'code')
    op.drop_column('mettable', 'activities')
    op.drop_column('mettable', 'heading')
    op.drop_column('mettable', 'met')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mettable', sa.Column('met', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mettable', sa.Column('heading', sa.VARCHAR(length=23), autoincrement=False, nullable=True))
    op.add_column('mettable', sa.Column('activities', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mettable', sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('mettable', 'METS')
    op.drop_column('mettable', 'HEADING')
    op.drop_column('mettable', 'CODE')
    op.drop_column('mettable', 'ACTIVITIES')
    op.drop_table('mets_table')
    # ### end Alembic commands ###
